version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Zagreb"
    labels:
      - "dependencies"
    open-pull-requests-limit: 2
    groups:
      npm-non-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
